version: "3.9"
services:
  mitsuakybot:
    build: .
    container_name: mitsuakybot
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - ./cogs:/bot/cogs
      - ./utils:/bot/utils
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "5431:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mitsuaky -d mitsuakybot"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  dbdata:
