version: "3.9"
services:
  mitsuakybot:
    build: .
    restart: unless-stopped
    pull_policy: build
    environment:
      DISCORD_PREFIX: ">"
      DISCORD_TOKEN:
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: mitsuaky
      POSTGRES_HOST: postgres
      POSTGRES_DB: mitsuakybot
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mitsuaky -d mitsuakybot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
