version: "3.9"

services:
  bot:
    build: .
    restart: unless-stopped
    pull_policy: build
    environment:
      - DOPPLER_TOKEN
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
