version: "3.9"
services:
  mitsuakybot:
    build: .
    container_name: mitsuakybot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - "postgres"

  postgres:
    build: ./postgres
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    